language: node_js
sudo: false
dist: trusty
cache:
  yarn: true
  directories:
  - node_modules
node_js:
  - "lts/*"
script:
  - npm run lint
  - npm run test
  - npm run dist
  - npm run build
after_success: 'npm run coveralls'

deploy:
  - provider: npm
    skip_cleanup: true
    email: "wxsms@foxmail.com"
    api_key: $NPM_TOKEN
    on:
      tags: true
  - provider: releases
    api_key: $GITHUB_TOKEN
    file:
      - "dist/uiv.min.js"
    skip_cleanup: true
    on:
      tags: true
  - provider: pages
    edge:
      branch: v1.8.47
    skip_cleanup: true
    github_token: $GITHUB_TOKEN
    local_dir: dist-docs
    on:
      branch: master
